name-template: "v$RESOLVED_VERSIONâ˜•"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "ğŸš€ Features"
    label: "type: feature"
  - title: "ğŸ› Bug Fixes"
    labels: "type: bug"
  - title: "ğŸ““ Documentation"
    labels: "type: docs"
  - title: "ğŸ”— dependencies"
    labels: "type: dependencies"
version-resolver:
  major:
    labels:
      - "type: breaking"
  minor:
    labels:
      - "type: feature"
  patch:
    labels:
      - "type: bug"
      - "type: docs"
      - "type: dependencies"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## Uncategorized 

  $CHANGES
