name-template: "v$NEXT_MINOR_VERSION ğŸŒˆ"
tag-template: "v$NEXT_MINOR_VERSION"
categories:
  - title: "ğŸš€ Features"
    label: "type: feature"
  - title: "ğŸ› Bug Fixes"
    labels: "type: bug"
  - title: "ğŸ““ Documentation"
    labels: "type: docs"
  - title: "ğŸ”— dependencies"
    labels: "type: dependencies"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## Uncategorized 

  $CHANGES
